# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Ong
tagline:          'Daniel Ong'
description:      'Machine learning, statistics, simulation, and whatever else I find interesting.'
url:              http://danielong.xyz
baseurl:          /

author:
  name:           'Daniel Ong'
  url:            https://github.com/danong/

paginate:         3
paginate_path:    "/blog/page:num/"
