# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Ong
tagline:          'Where does this show up?'
description:      'I put my CS related blog posts and project information here.'
url:              http://danielong.xyz
baseurl:          /

author:
  name:           'Daniel Ong'
  url:            http://danielong.xyz

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/danong/danong.github.io
