# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Ong
tagline:          'Daniel Ong'
description:      'I put my CS stuff here.'
url:              http://danielong.xyz
baseurl:          /

author:
  name:           'Daniel Ong'
  url:            https://github.com/danong/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/danong/danong.github.io
